sicken-openai_llm:
  request_responded:
    sicken-speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-vtube_plugin_speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-standalone_speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture
  
    sicken-gui_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-twitch_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-webchat_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-subtitles:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture


sicken-agent_server:
  command_executed:
    sicken-agent_command_execution_response:
      command_uuid: command_uuid
      command: command
      exit_code: exit_code
      stdout: stdout
      stderr: stderr
      
  terminal_snapshot:
    sicken-agent_terminal_snapshot_response:
      process_uuid: command_uuid
      command: command
      terminal_snapshot: terminal_snapshot

sicken-openai_llm_commands:
  execute_command:
    sicken-agent_command_execution_requests:
      command_uuid: command_uuid
      command: command

  command_feedback:
    sicken-gui_commands_feedback:
      message: message
      
  request_responded:
    sicken-speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-vtube_plugin_speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-standalone_speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture
  
    sicken-gui_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-twitch_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-webchat_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-subtitles:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture


sicken-ollama_llm:
  request_responded:
    sicken-speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-vtube_plugin_speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-standalone_speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-gui_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-twitch_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-webchat_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-subtitles:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture


sicken-grok_llm:
  request_responded:
    sicken-speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-vtube_plugin_speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-standalone_speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture
  
    sicken-gui_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-twitch_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-webchat_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-subtitles:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture



sicken-deepseek_llm:
  request_responded:
    sicken-speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-vtube_plugin_speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-standalone_speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-gui_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-twitch_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture
      
    sicken-webchat_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-subtitles:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

sicken-gui_standalone:
  message_entered:
    sicken-response_requests:
      chat_uuid: chat_uuid
      message_author: message_author
      message_source: message_source
      message: message

    sicken-classification_requests:
      chat_uuid: chat_uuid
      message_author: profile_user_name
      message_source: profile_platform
      message: message

    sicken-webchat_requests:
      chat_uuid: chat_uuid
      message_author: message_author
      message_source: message_source
      message: message
      
  model_introduction:
    sicken-model_introduction:
      model_name: model_name
      model_id: model_id
      actions: actions

sicken-gui_vtube_studio:
  message_entered:
    sicken-response_requests:
      chat_uuid: chat_uuid
      message_author: message_author
      message_source: message_source
      message: message

    sicken-classification_requests:
      chat_uuid: chat_uuid
      message_author: profile_user_name
      message_source: profile_platform
      message: message

    sicken-webchat_requests:
      chat_uuid: chat_uuid
      message_author: message_author
      message_source: message_source
      message: message
      
  model_introduction:
    sicken-model_introduction:
      model_name: model_name
      model_id: model_id
      actions: actions

  command_entered:
    sicken-command_requests:
      chat_uuid: chat_uuid
      message_author: message_author
      message_source: message_source
      cmd: cmd
      args: args

sicken-twitch_chat:
  message_entered:
    sicken-response_requests:
      chat_uuid: chat_uuid
      message_author: message_author
      message_source: message_source
      message: message
      
    sicken-classification_requests:
      chat_uuid: chat_uuid
      message_author: profile_user_name
      message_source: profile_platform
      message: message

    sicken-webchat_requests:
      chat_uuid: chat_uuid
      message_author: message_author
      message_source: message_source
      message: message

sicken-tiktok_chat:
  message_entered:
    sicken-response_requests:
      chat_uuid: chat_uuid
      message_author: message_author
      message_source: message_source
      message: message
      
    sicken-classification_requests:
      chat_uuid: chat_uuid
      message_author: profile_user_name
      message_source: profile_platform
      message: message

    sicken-webchat_requests:
      chat_uuid: chat_uuid
      message_author: message_author
      message_source: message_source
      message: message

sicken-speech_generator_openai:
  speech_generated:
    sicken-standalone_speech_generation_finished:
      response_uuid: response_uuid
      speech_duration: speech_duration
      speech_words: speech_words

    sicken-vtube_plugin_speech_generation_finished:
      response_uuid: response_uuid
      speech_duration: speech_duration
      speech_words: speech_words

  model_introduction:
      sicken-model_introduction:
        model_name: model_name
        model_id: model_id
        actions: actions

sicken-vtube_plugin:
  model_introduction:
    sicken-model_introduction:
      model_name: model_name
      model_id: model_id
      actions: actions

  command_feedback:
    sicken-command_feedback:
      message: message

sicken-commands:
  command_feedback:
    sicken-gui_commands_feedback:
      message: message

  load_model:
    sicken-vtube_plugin_load_model_requests:
      model: model

  gesture:
    sicken-vtube_plugin_speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture