sicken-openai_llm:
  request_responded:
    sicken-speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-vtube_plugin_speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-gui_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-twitch_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

  model_introduction_request:
    sicken-model_introduction_requests:

sicken-ollama_llm:
  request_responded:
    sicken-speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-vtube_plugin_speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-gui_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-twitch_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

  model_introduction_request:
    sicken-model_introduction_requests:

sicken-grok_llm:
  request_responded:
    sicken-speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-vtube_plugin_speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-gui_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-twitch_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

  model_introduction_request:
    sicken-model_introduction_requests:

sicken-deepseek_llm:
  request_responded:
    sicken-speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-vtube_plugin_speech_requests:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-gui_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

    sicken-twitch_responses:
      response_uuid: response_uuid
      chat_uuid: chat_uuid
      message_author: message_author
      message: message
      speech: speech
      gesture: gesture

  model_introduction_request:
    sicken-model_introduction_requests:

sicken-microphone_input:
  speech_recognized:
    sicken-response_requests:
      chat_uuid: chat_uuid
      message_author: message_author
      message: message

sicken-text_input:
  message_entered:
    sicken-response_requests:
      chat_uuid: chat_uuid
      message_author: message_author
      message_source: message_source
      message: message

sicken-gui:
  message_entered:
    sicken-response_requests:
      chat_uuid: chat_uuid
      message_author: message_author
      message_source: message_source
      message: message

    sicken-classification_requests:
      chat_uuid: chat_uuid
      message_author: profile_user_name
      message_source: profile_platform
      message: message


sicken-twitch_chat:
  message_entered:
    sicken-response_requests:
      chat_uuid: chat_uuid
      message_author: message_author
      message_source: message_source
      message: message
      
    sicken-classification_requests:
      chat_uuid: chat_uuid
      message_author: profile_user_name
      message_source: profile_platform
      message: message

sicken-speech_generator:
  speech_generated:
    sicken-vtube_plugin_speech_generation_finished:
      response_uuid: response_uuid
      speech_duration: speech_duration
      speech_words: speech_words

sicken-vtube_plugin:
  model_introduction:
    sicken-model_introduction:
      model_name: model_name
      model_id: model_id
      actions: actions
