window:
  width: 400
  height: 1080

log:
  debug: true

scheduler:
    interval: 0.1
    
mongo:
  host: localhost
  port: 27017
  db: sicken

rabbitmq:
  host: localhost
  port: 5672
  user: sicken-chat_viewer
  password: password
