model:
  model: akari

vtube:
  host: localhost
  port: 8001
  frame_duration: 0.067
  whisper_lip_data: true

log:
  debug: false

mongo:
  host: localhost
  port: 27017
  db: sicken

rabbitmq:
  host: localhost
  port: 5672
  user: sicken-vtube_plugin
  password: password
  
directories_posix:
  speech: /opt/sicken/files/sicken/speech
  live2d_models: /opt/sicken/live2d_models

directories_nt:
  speech: "C:\\sicken\\files\\sicken\\speech"
  live2d_models: "c:\\sicken\\live2d_models"