model:
  model_id: 31f896f000364f4fb02034761b2e9a3e

vtube:
  host: localhost
  port: 8001

log:
  debug: true

mongo:
  host: localhost
  port: 27017
  db: sicken

rabbitmq:
  host: localhost
  port: 5672
  user: sicken-vtube_plugin
  password: password
  
directories:
  speech: /opt/sicken/files/sicken/speech