sicken-log_worker:
  enable: true
  workers_count: 1
  uid: 7676
  gid: 7676

sicken-events:
  enable: true
  workers_count: 1
  uid: 7676
  gid: 7676

sicken-openai_llm:
  enable: true
  workers_count: 1
  uid: 7676
  gid: 7676

sicken-deepseek_llm:
  enable: false
  workers_count: 1
  uid: 7676
  gid: 7676

sicken-grok_llm:
  enable: false
  workers_count: 1
  uid: 7676
  gid: 7676


sicken-ollama_llm:
  enable: false
  workers_count: 1
  uid: 7676
  gid: 7676

sicken-speech_generator:
  enable: true
  workers_count: 1
  uid: 7676
  gid: 7676

sicken-vtube_plugin:
  enable: true
  workers_count: 1
  uid: 7676
  gid: 7676

sicken-gui:
  enable: true
  workers_count: 1
  uid: 7676
  gid: 7676

sicken-classification:
  enable: true
  workers_count: 5
  uid: 7676
  gid: 7676

sicken-twitch_chat:
  enable: false
  workers_count: 1
  uid: 7676
  gid: 7676
